// <auto-generated />
using System;
using FMBot.Persistence.EntityFrameWork;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FMBot.Persistence.EntityFrameWork.Migrations
{
    [DbContext(typeof(FMBotDbContext))]
    [Migration("20230108205436_AddFooterOptions")]
    partial class AddFooterOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "timescaledb");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<string>("ArtistName")
                        .HasColumnType("citext")
                        .HasColumnName("artist_name");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("LastFmUrl")
                        .HasColumnType("text")
                        .HasColumnName("last_fm_url");

                    b.Property<DateTime?>("LastfmDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastfm_date");

                    b.Property<string>("LastfmImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("lastfm_image_url");

                    b.Property<Guid?>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<string>("Name")
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<int?>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("text")
                        .HasColumnName("release_date");

                    b.Property<string>("ReleaseDatePrecision")
                        .HasColumnType("text")
                        .HasColumnName("release_date_precision");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("text")
                        .HasColumnName("spotify_id");

                    b.Property<DateTime?>("SpotifyImageDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("spotify_image_date");

                    b.Property<string>("SpotifyImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("spotify_image_url");

                    b.HasKey("Id")
                        .HasName("pk_albums");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_albums_artist_id");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<string>("Disambiguation")
                        .HasColumnType("text")
                        .HasColumnName("disambiguation");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("LastFmUrl")
                        .HasColumnType("text")
                        .HasColumnName("last_fm_url");

                    b.Property<DateTime?>("LastfmDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastfm_date");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<Guid?>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<DateTime?>("MusicBrainzDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("music_brainz_date");

                    b.Property<string>("Name")
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<int?>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("text")
                        .HasColumnName("spotify_id");

                    b.Property<DateTime?>("SpotifyImageDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("spotify_image_date");

                    b.Property<string>("SpotifyImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("spotify_image_url");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_artists");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.ArtistAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<bool>("CorrectsInScrobbles")
                        .HasColumnType("boolean")
                        .HasColumnName("corrects_in_scrobbles");

                    b.HasKey("Id")
                        .HasName("pk_artist_aliases");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_artist_aliases_artist_id");

                    b.ToTable("artist_aliases", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.ArtistGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<string>("Name")
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_artist_genres");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_artist_genres_artist_id");

                    b.ToTable("artist_genres", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.BottedUser", b =>
                {
                    b.Property<int>("BottedUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("botted_user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BottedUserId"));

                    b.Property<bool>("BanActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ban_active");

                    b.Property<DateTime?>("LastFmRegistered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fm_registered");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("UserNameLastFM")
                        .HasColumnType("text")
                        .HasColumnName("user_name_last_fm");

                    b.HasKey("BottedUserId")
                        .HasName("pk_botted_users");

                    b.ToTable("botted_users", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.CensoredMusic", b =>
                {
                    b.Property<int>("CensoredMusicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("censored_music_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CensoredMusicId"));

                    b.Property<string>("AlbumName")
                        .HasColumnType("text")
                        .HasColumnName("album_name");

                    b.Property<string>("AlternativeCoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("alternative_cover_url");

                    b.Property<bool>("Artist")
                        .HasColumnType("boolean")
                        .HasColumnName("artist");

                    b.Property<string>("ArtistName")
                        .HasColumnType("text")
                        .HasColumnName("artist_name");

                    b.Property<bool?>("FeaturedBanOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("featured_ban_only");

                    b.Property<bool>("SafeForCommands")
                        .HasColumnType("boolean")
                        .HasColumnName("safe_for_commands");

                    b.Property<bool>("SafeForFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("safe_for_featured");

                    b.Property<int?>("TimesCensored")
                        .HasColumnType("integer")
                        .HasColumnName("times_censored");

                    b.HasKey("CensoredMusicId")
                        .HasName("pk_censored_music");

                    b.ToTable("censored_music", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChannelId"));

                    b.Property<string>("DisabledCommands")
                        .HasColumnType("text")
                        .HasColumnName("disabled_commands");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_channel_id");

                    b.Property<int?>("FmCooldown")
                        .HasColumnType("integer")
                        .HasColumnName("fm_cooldown");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ChannelId")
                        .HasName("pk_channels");

                    b.HasIndex("DiscordChannelId")
                        .HasDatabaseName("ix_channels_discord_channel_id");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_channels_guild_id");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.DiscogsFormatDescriptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("citext")
                        .HasColumnName("description");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer")
                        .HasColumnName("release_id");

                    b.HasKey("Id")
                        .HasName("pk_discogs_format_descriptions");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_discogs_format_descriptions_release_id");

                    b.ToTable("discogs_format_descriptions", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.DiscogsGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("citext")
                        .HasColumnName("description");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer")
                        .HasColumnName("release_id");

                    b.HasKey("Id")
                        .HasName("pk_discogs_genre");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_discogs_genre_release_id");

                    b.ToTable("discogs_genre", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.DiscogsRelease", b =>
                {
                    b.Property<int>("DiscogsId")
                        .HasColumnType("integer")
                        .HasColumnName("discogs_id");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("album_id");

                    b.Property<string>("Artist")
                        .HasColumnType("citext")
                        .HasColumnName("artist");

                    b.Property<int>("ArtistDiscogsId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_discogs_id");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<string>("FeaturingArtist")
                        .HasColumnType("citext")
                        .HasColumnName("featuring_artist");

                    b.Property<int?>("FeaturingArtistDiscogsId")
                        .HasColumnType("integer")
                        .HasColumnName("featuring_artist_discogs_id");

                    b.Property<int?>("FeaturingArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("featuring_artist_id");

                    b.Property<string>("FeaturingArtistJoin")
                        .HasColumnType("text")
                        .HasColumnName("featuring_artist_join");

                    b.Property<string>("Format")
                        .HasColumnType("citext")
                        .HasColumnName("format");

                    b.Property<string>("FormatText")
                        .HasColumnType("text")
                        .HasColumnName("format_text");

                    b.Property<string>("Label")
                        .HasColumnType("citext")
                        .HasColumnName("label");

                    b.Property<decimal?>("LowestPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("lowest_price");

                    b.Property<int?>("MasterId")
                        .HasColumnType("integer")
                        .HasColumnName("master_id");

                    b.Property<string>("SecondLabel")
                        .HasColumnType("text")
                        .HasColumnName("second_label");

                    b.Property<string>("Title")
                        .HasColumnType("citext")
                        .HasColumnName("title");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("DiscogsId")
                        .HasName("pk_discogs_releases");

                    b.ToTable("discogs_releases", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.DiscogsStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("citext")
                        .HasColumnName("description");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer")
                        .HasColumnName("release_id");

                    b.HasKey("Id")
                        .HasName("pk_discogs_style");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_discogs_style_release_id");

                    b.ToTable("discogs_style", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.FeaturedLog", b =>
                {
                    b.Property<int>("FeaturedLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("featured_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeaturedLogId"));

                    b.Property<string>("AlbumName")
                        .HasColumnType("citext")
                        .HasColumnName("album_name");

                    b.Property<string>("ArtistName")
                        .HasColumnType("citext")
                        .HasColumnName("artist_name");

                    b.Property<int>("BotType")
                        .HasColumnType("integer")
                        .HasColumnName("bot_type");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FeaturedMode")
                        .HasColumnType("integer")
                        .HasColumnName("featured_mode");

                    b.Property<bool>("HasFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("has_featured");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool?>("NoUpdate")
                        .HasColumnType("boolean")
                        .HasColumnName("no_update");

                    b.Property<bool>("SupporterDay")
                        .HasColumnType("boolean")
                        .HasColumnName("supporter_day");

                    b.Property<string>("TrackName")
                        .HasColumnType("citext")
                        .HasColumnName("track_name");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("FeaturedLogId")
                        .HasName("pk_featured_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_featured_logs_user_id");

                    b.ToTable("featured_logs", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Friend", b =>
                {
                    b.Property<int>("FriendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("friend_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FriendId"));

                    b.Property<int?>("FriendUserId")
                        .HasColumnType("integer")
                        .HasColumnName("friend_user_id");

                    b.Property<string>("LastFMUserName")
                        .HasColumnType("text")
                        .HasColumnName("last_fm_user_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("FriendId")
                        .HasName("pk_friends");

                    b.HasIndex("FriendUserId")
                        .HasDatabaseName("ix_friends_friend_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_friends_user_id");

                    b.ToTable("friends", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Guild", b =>
                {
                    b.Property<int>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("guild_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GuildId"));

                    b.Property<int?>("ActivityThresholdDays")
                        .HasColumnType("integer")
                        .HasColumnName("activity_threshold_days");

                    b.Property<bool?>("Blacklisted")
                        .HasColumnType("boolean")
                        .HasColumnName("blacklisted");

                    b.Property<int?>("ChartTimePeriod")
                        .HasColumnType("integer")
                        .HasColumnName("chart_time_period");

                    b.Property<int?>("CrownsActivityThresholdDays")
                        .HasColumnType("integer")
                        .HasColumnName("crowns_activity_threshold_days");

                    b.Property<bool?>("CrownsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("crowns_disabled");

                    b.Property<int?>("CrownsMinimumPlaycountThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("crowns_minimum_playcount_threshold");

                    b.Property<bool?>("DisableSupporterMessages")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_supporter_messages");

                    b.Property<string>("DisabledCommands")
                        .HasColumnType("text")
                        .HasColumnName("disabled_commands");

                    b.Property<decimal>("DiscordGuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_guild_id");

                    b.Property<string>("EmoteReactions")
                        .HasColumnType("text")
                        .HasColumnName("emote_reactions");

                    b.Property<int?>("FmEmbedType")
                        .HasColumnType("integer")
                        .HasColumnName("fm_embed_type");

                    b.Property<DateTime?>("LastIndexed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_indexed");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<bool?>("SpecialGuild")
                        .HasColumnType("boolean")
                        .HasColumnName("special_guild");

                    b.Property<bool?>("TitlesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("titles_enabled");

                    b.Property<decimal?>("WhoKnowsWhitelistRoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("who_knows_whitelist_role_id");

                    b.HasKey("GuildId")
                        .HasName("pk_guilds");

                    b.HasIndex("DiscordGuildId")
                        .HasDatabaseName("ix_guilds_discord_guild_id");

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.GuildBlockedUser", b =>
                {
                    b.Property<int>("GuildId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<bool>("BlockedFromCrowns")
                        .HasColumnType("boolean")
                        .HasColumnName("blocked_from_crowns");

                    b.Property<bool>("BlockedFromWhoKnows")
                        .HasColumnType("boolean")
                        .HasColumnName("blocked_from_who_knows");

                    b.Property<bool>("SelfBlockFromWhoKnows")
                        .HasColumnType("boolean")
                        .HasColumnName("self_block_from_who_knows");

                    b.HasKey("GuildId", "UserId")
                        .HasName("pk_guild_blocked_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_guild_blocked_users_user_id");

                    b.ToTable("guild_blocked_users", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.GuildUser", b =>
                {
                    b.Property<int>("GuildId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<bool?>("Bot")
                        .HasColumnType("boolean")
                        .HasColumnName("bot");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.Property<bool?>("WhoKnowsWhitelisted")
                        .HasColumnType("boolean")
                        .HasColumnName("who_knows_whitelisted");

                    b.HasKey("GuildId", "UserId")
                        .HasName("pk_guild_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_guild_users_user_id");

                    b.ToTable("guild_users", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.InactiveUsers", b =>
                {
                    b.Property<int>("InactiveUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inactive_user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InactiveUserId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<int?>("FailureErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("failure_error_count");

                    b.Property<int?>("MissingParametersErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("missing_parameters_error_count");

                    b.Property<int?>("NoScrobblesErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("no_scrobbles_error_count");

                    b.Property<int?>("RecentTracksPrivateCount")
                        .HasColumnType("integer")
                        .HasColumnName("recent_tracks_private_count");

                    b.Property<bool?>("Removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer")
                        .HasColumnName("user_id1");

                    b.Property<string>("UserNameLastFM")
                        .HasColumnType("text")
                        .HasColumnName("user_name_last_fm");

                    b.HasKey("InactiveUserId")
                        .HasName("pk_inactive_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_inactive_users_user_id");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("ix_inactive_users_user_id1");

                    b.ToTable("inactive_users", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("supporter_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupporterId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<decimal?>("DiscordUserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_user_id");

                    b.Property<bool?>("Expired")
                        .HasColumnType("boolean")
                        .HasColumnName("expired");

                    b.Property<DateTime?>("LastPayment")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_payment");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OpenCollectiveId")
                        .HasColumnType("text")
                        .HasColumnName("open_collective_id");

                    b.Property<int?>("SubscriptionType")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_type");

                    b.Property<bool>("SupporterMessagesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("supporter_messages_enabled");

                    b.Property<int>("SupporterType")
                        .HasColumnType("integer")
                        .HasColumnName("supporter_type");

                    b.Property<bool>("VisibleInOverview")
                        .HasColumnType("boolean")
                        .HasColumnName("visible_in_overview");

                    b.HasKey("SupporterId")
                        .HasName("pk_supporters");

                    b.ToTable("supporters", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("Acousticness")
                        .HasColumnType("real")
                        .HasColumnName("acousticness");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("album_id");

                    b.Property<string>("AlbumName")
                        .HasColumnType("citext")
                        .HasColumnName("album_name");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<string>("ArtistName")
                        .HasColumnType("citext")
                        .HasColumnName("artist_name");

                    b.Property<float?>("Danceability")
                        .HasColumnType("real")
                        .HasColumnName("danceability");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<float?>("Energy")
                        .HasColumnType("real")
                        .HasColumnName("energy");

                    b.Property<float?>("Instrumentalness")
                        .HasColumnType("real")
                        .HasColumnName("instrumentalness");

                    b.Property<int?>("Key")
                        .HasColumnType("integer")
                        .HasColumnName("key");

                    b.Property<string>("LastFmUrl")
                        .HasColumnType("text")
                        .HasColumnName("last_fm_url");

                    b.Property<DateTime?>("LastfmDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastfm_date");

                    b.Property<float?>("Liveness")
                        .HasColumnType("real")
                        .HasColumnName("liveness");

                    b.Property<float?>("Loudness")
                        .HasColumnType("real")
                        .HasColumnName("loudness");

                    b.Property<Guid?>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<string>("Name")
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<int?>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<float?>("Speechiness")
                        .HasColumnType("real")
                        .HasColumnName("speechiness");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("text")
                        .HasColumnName("spotify_id");

                    b.Property<DateTime?>("SpotifyLastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("spotify_last_updated");

                    b.Property<float?>("Tempo")
                        .HasColumnType("real")
                        .HasColumnName("tempo");

                    b.Property<float?>("Valence")
                        .HasColumnType("real")
                        .HasColumnName("valence");

                    b.HasKey("Id")
                        .HasName("pk_tracks");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("ix_tracks_album_id");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_tracks_artist_id");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool?>("Blocked")
                        .HasColumnType("boolean")
                        .HasColumnName("blocked");

                    b.Property<int>("DataSource")
                        .HasColumnType("integer")
                        .HasColumnName("data_source");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_user_id");

                    b.Property<int?>("FmCountType")
                        .HasColumnType("integer")
                        .HasColumnName("fm_count_type");

                    b.Property<int>("FmEmbedType")
                        .HasColumnType("integer")
                        .HasColumnName("fm_embed_type");

                    b.Property<long>("FmFmFooterOptions")
                        .HasColumnType("bigint")
                        .HasColumnName("fm_fm_footer_options");

                    b.Property<DateTime?>("LastIndexed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_indexed");

                    b.Property<DateTime?>("LastScrobbleUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scrobble_update");

                    b.Property<DateTime?>("LastSmallIndexed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_small_indexed");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used");

                    b.Property<bool?>("LastfmPro")
                        .HasColumnType("boolean")
                        .HasColumnName("lastfm_pro");

                    b.Property<int?>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<bool?>("MusicBotTrackingDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("music_bot_tracking_disabled");

                    b.Property<int>("PrivacyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("privacy_level");

                    b.Property<DateTime?>("RegisteredLastFm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_last_fm");

                    b.Property<bool?>("RymEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("rym_enabled");

                    b.Property<string>("SessionKeyLastFm")
                        .HasColumnType("text")
                        .HasColumnName("session_key_last_fm");

                    b.Property<long?>("TotalPlaycount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_playcount");

                    b.Property<string>("UserNameLastFM")
                        .HasColumnType("text")
                        .HasColumnName("user_name_last_fm");

                    b.Property<int>("UserType")
                        .HasColumnType("integer")
                        .HasColumnName("user_type");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("DiscordUserId")
                        .HasDatabaseName("ix_users_discord_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_users_user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserAlbum", b =>
                {
                    b.Property<long>("UserAlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_album_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserAlbumId"));

                    b.Property<string>("ArtistName")
                        .HasColumnType("citext")
                        .HasColumnName("artist_name");

                    b.Property<string>("Name")
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<int>("Playcount")
                        .HasColumnType("integer")
                        .HasColumnName("playcount");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("UserAlbumId")
                        .HasName("pk_user_albums");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_albums_user_id");

                    b.ToTable("user_albums", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserArtist", b =>
                {
                    b.Property<long>("UserArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_artist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserArtistId"));

                    b.Property<string>("Name")
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<int>("Playcount")
                        .HasColumnType("integer")
                        .HasColumnName("playcount");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("UserArtistId")
                        .HasName("pk_user_artists");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_artists_user_id");

                    b.ToTable("user_artists", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserCrown", b =>
                {
                    b.Property<int>("CrownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("crown_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CrownId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ArtistName")
                        .HasColumnType("citext")
                        .HasColumnName("artist_name");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<int>("CurrentPlaycount")
                        .HasColumnType("integer")
                        .HasColumnName("current_playcount");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_id");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<bool>("SeededCrown")
                        .HasColumnType("boolean")
                        .HasColumnName("seeded_crown");

                    b.Property<int>("StartPlaycount")
                        .HasColumnType("integer")
                        .HasColumnName("start_playcount");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("CrownId")
                        .HasName("pk_user_crowns");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_user_crowns_guild_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_crowns_user_id");

                    b.ToTable("user_crowns", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserDiscogs", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<string>("AccessTokenSecret")
                        .HasColumnType("text")
                        .HasColumnName("access_token_secret");

                    b.Property<int>("DiscogsId")
                        .HasColumnType("integer")
                        .HasColumnName("discogs_id");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("MaximumValue")
                        .HasColumnType("text")
                        .HasColumnName("maximum_value");

                    b.Property<string>("MedianValue")
                        .HasColumnType("text")
                        .HasColumnName("median_value");

                    b.Property<string>("MinimumValue")
                        .HasColumnType("text")
                        .HasColumnName("minimum_value");

                    b.Property<DateTime?>("ReleasesLastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("releases_last_updated");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_user_discogs");

                    b.ToTable("user_discogs", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserDiscogsReleases", b =>
                {
                    b.Property<int>("UserDiscogsReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_discogs_release_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserDiscogsReleaseId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added");

                    b.Property<int>("InstanceId")
                        .HasColumnType("integer")
                        .HasColumnName("instance_id");

                    b.Property<string>("Quantity")
                        .HasColumnType("text")
                        .HasColumnName("quantity");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer")
                        .HasColumnName("release_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("UserDiscogsReleaseId")
                        .HasName("pk_user_discogs_releases");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_user_discogs_releases_release_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_discogs_releases_user_id");

                    b.ToTable("user_discogs_releases", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserPlay", b =>
                {
                    b.Property<long>("UserPlayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_play_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserPlayId"));

                    b.Property<string>("AlbumName")
                        .HasColumnType("citext")
                        .HasColumnName("album_name");

                    b.Property<string>("ArtistName")
                        .HasColumnType("citext")
                        .HasColumnName("artist_name");

                    b.Property<DateTime>("TimePlayed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_played");

                    b.Property<string>("TrackName")
                        .HasColumnType("citext")
                        .HasColumnName("track_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("UserPlayId")
                        .HasName("pk_user_plays");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_plays_user_id");

                    b.ToTable("user_plays", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserPlayTs", b =>
                {
                    b.Property<string>("AlbumName")
                        .HasColumnType("citext")
                        .HasColumnName("album_name");

                    b.Property<string>("ArtistName")
                        .HasColumnType("citext")
                        .HasColumnName("artist_name");

                    b.Property<DateTime>("TimePlayed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_played");

                    b.Property<string>("TrackName")
                        .HasColumnType("citext")
                        .HasColumnName("track_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_play_ts_user_id");

                    b.ToTable("user_play_ts", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserStreak", b =>
                {
                    b.Property<long>("UserStreakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_streak_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserStreakId"));

                    b.Property<string>("AlbumName")
                        .HasColumnType("citext")
                        .HasColumnName("album_name");

                    b.Property<int?>("AlbumPlaycount")
                        .HasColumnType("integer")
                        .HasColumnName("album_playcount");

                    b.Property<string>("ArtistName")
                        .HasColumnType("citext")
                        .HasColumnName("artist_name");

                    b.Property<int?>("ArtistPlaycount")
                        .HasColumnType("integer")
                        .HasColumnName("artist_playcount");

                    b.Property<DateTime>("StreakEnded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("streak_ended");

                    b.Property<DateTime>("StreakStarted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("streak_started");

                    b.Property<string>("TrackName")
                        .HasColumnType("citext")
                        .HasColumnName("track_name");

                    b.Property<int?>("TrackPlaycount")
                        .HasColumnType("integer")
                        .HasColumnName("track_playcount");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("UserStreakId")
                        .HasName("pk_user_streaks");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_streaks_user_id");

                    b.ToTable("user_streaks", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserTrack", b =>
                {
                    b.Property<long>("UserTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_track_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserTrackId"));

                    b.Property<string>("ArtistName")
                        .HasColumnType("citext")
                        .HasColumnName("artist_name");

                    b.Property<string>("Name")
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<int>("Playcount")
                        .HasColumnType("integer")
                        .HasColumnName("playcount");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("UserTrackId")
                        .HasName("pk_user_tracks");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_tracks_user_id");

                    b.ToTable("user_tracks", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Webhook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BotType")
                        .HasColumnType("integer")
                        .HasColumnName("bot_type");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<decimal>("DiscordWebhookId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_webhook_id");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_id");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_webhooks");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_webhooks_guild_id");

                    b.ToTable("webhooks", (string)null);
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Album", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .HasConstraintName("fk_albums_artists_artist_id");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.ArtistAlias", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.Artist", "Artist")
                        .WithMany("ArtistAliases")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_aliases_artists_artist_id");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.ArtistGenre", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.Artist", "Artist")
                        .WithMany("ArtistGenres")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_genres_artists_artist_id");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Channel", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.Guild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channels_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.DiscogsFormatDescriptions", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.DiscogsRelease", "DiscogsRelease")
                        .WithMany("FormatDescriptions")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discogs_format_descriptions_discogs_releases_discogs_releas");

                    b.Navigation("DiscogsRelease");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.DiscogsGenre", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.DiscogsRelease", "DiscogsRelease")
                        .WithMany("Genres")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discogs_genre_discogs_releases_discogs_release_temp_id1");

                    b.Navigation("DiscogsRelease");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.DiscogsStyle", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.DiscogsRelease", "DiscogsRelease")
                        .WithMany("Styles")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discogs_style_discogs_releases_discogs_release_temp_id2");

                    b.Navigation("DiscogsRelease");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.FeaturedLog", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithMany("FeaturedLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_featured_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Friend", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.User", "FriendUser")
                        .WithMany("FriendedByUsers")
                        .HasForeignKey("FriendUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK.Friends.Users_FriendUserID");

                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK.Friends.Users_UserID");

                    b.Navigation("FriendUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.GuildBlockedUser", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.Guild", "Guild")
                        .WithMany("GuildBlockedUsers")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_blocked_users_guilds_guild_id");

                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithMany("GuildBlockedUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_blocked_users_users_user_id");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.GuildUser", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.Guild", "Guild")
                        .WithMany("GuildUsers")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_users_guilds_guild_id");

                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithMany("GuildUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_users_users_user_id");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.InactiveUsers", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_inactive_users_users_user_id");

                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .HasConstraintName("fk_inactive_users_users_user_id1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Track", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("fk_tracks_albums_album_id");

                    b.HasOne("FMBot.Persistence.Domain.Models.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .HasConstraintName("fk_tracks_artists_artist_id");

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserAlbum", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithMany("Albums")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_albums_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserArtist", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithMany("Artists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_artists_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserCrown", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.Guild", "Guild")
                        .WithMany("GuildCrowns")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_crowns_guilds_guild_id");

                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithMany("Crowns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_crowns_users_user_id");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserDiscogs", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithOne("UserDiscogs")
                        .HasForeignKey("FMBot.Persistence.Domain.Models.UserDiscogs", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_discogs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserDiscogsReleases", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.DiscogsRelease", "Release")
                        .WithMany("UserDiscogsReleases")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_discogs_releases_discogs_releases_release_id");

                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithMany("DiscogsReleases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_discogs_releases_users_user_id");

                    b.Navigation("Release");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserPlay", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithMany("Plays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_plays_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserStreak", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithMany("Streaks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_streaks_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.UserTrack", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.User", "User")
                        .WithMany("Tracks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tracks_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Webhook", b =>
                {
                    b.HasOne("FMBot.Persistence.Domain.Models.Guild", "Guild")
                        .WithMany("Webhooks")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_webhooks_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("ArtistAliases");

                    b.Navigation("ArtistGenres");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.DiscogsRelease", b =>
                {
                    b.Navigation("FormatDescriptions");

                    b.Navigation("Genres");

                    b.Navigation("Styles");

                    b.Navigation("UserDiscogsReleases");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.Guild", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("GuildBlockedUsers");

                    b.Navigation("GuildCrowns");

                    b.Navigation("GuildUsers");

                    b.Navigation("Webhooks");
                });

            modelBuilder.Entity("FMBot.Persistence.Domain.Models.User", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Artists");

                    b.Navigation("Crowns");

                    b.Navigation("DiscogsReleases");

                    b.Navigation("FeaturedLogs");

                    b.Navigation("FriendedByUsers");

                    b.Navigation("Friends");

                    b.Navigation("GuildBlockedUsers");

                    b.Navigation("GuildUsers");

                    b.Navigation("Plays");

                    b.Navigation("Streaks");

                    b.Navigation("Tracks");

                    b.Navigation("UserDiscogs");
                });
#pragma warning restore 612, 618
        }
    }
}
