// <auto-generated />

using System;
using FMBot.Persistence.EntityFrameWork;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace FMBot.DbMigration.OldDatabase.Migrations
{
    [DbContext(typeof(FMBotDbContext))]
    [Migration("20190916110715_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FMBot.Data.Entities.Friend", b =>
                {
                    b.Property<int>("FriendID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("FriendID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FriendUserID")
                        .HasColumnName("FriendUserID");

                    b.Property<string>("LastFMUserName")
                        .HasColumnName("LastFMUserName");

                    b.Property<int>("UserID")
                        .HasColumnName("UserID");

                    b.HasKey("FriendID")
                        .HasName("PK_dbo.Friends");

                    b.HasIndex("FriendUserID")
                        .HasName("IX_FriendUserID");

                    b.HasIndex("UserID")
                        .HasName("IX_UserID");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("FMBot.Data.Entities.Guild", b =>
                {
                    b.Property<int>("GuildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GuildID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Blacklisted");

                    b.Property<int>("ChartTimePeriod");

                    b.Property<int>("ChartType");

                    b.Property<string>("DiscordGuildID")
                        .HasColumnName("DiscordGuildID");

                    b.Property<string>("Name");

                    b.Property<bool?>("TitlesEnabled");

                    b.HasKey("GuildID")
                        .HasName("PK_dbo.Guilds");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("FMBot.Data.Entities.GuildUsers", b =>
                {
                    b.Property<int>("GuildID")
                        .HasColumnName("GuildID");

                    b.Property<int>("UserID")
                        .HasColumnName("UserID");

                    b.HasKey("GuildID", "UserID")
                        .HasName("PK_dbo.GuildUsers");

                    b.HasIndex("GuildID")
                        .HasName("IX_GuildID");

                    b.HasIndex("UserID")
                        .HasName("IX_UserID");

                    b.ToTable("GuildUsers");
                });

            modelBuilder.Entity("FMBot.Data.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Blacklisted");

                    b.Property<int>("ChartTimePeriod");

                    b.Property<int>("ChartType");

                    b.Property<string>("DiscordUserID")
                        .HasColumnName("DiscordUserID");

                    b.Property<bool?>("Featured");

                    b.Property<DateTime?>("LastGeneratedChartDateTimeUtc")
                        .HasColumnType("datetime");

                    b.Property<bool?>("TitlesEnabled");

                    b.Property<string>("UserNameLastFM")
                        .HasColumnName("UserNameLastFM");

                    b.Property<int>("UserType");

                    b.HasKey("UserID")
                        .HasName("PK_dbo.Users");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FMBot.Data.Entities.Friend", b =>
                {
                    b.HasOne("FMBot.Data.Entities.User", "FriendUser")
                        .WithMany("FriendsFriendUser")
                        .HasForeignKey("FriendUserID")
                        .HasConstraintName("FK_dbo.Friends_dbo.Users_FriendUserID");

                    b.HasOne("FMBot.Data.Entities.User", "User")
                        .WithMany("FriendsUser")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK_dbo.Friends_dbo.Users_UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FMBot.Data.Entities.GuildUsers", b =>
                {
                    b.HasOne("FMBot.Data.Entities.Guild", "Guild")
                        .WithMany("GuildUsers")
                        .HasForeignKey("GuildID")
                        .HasConstraintName("FK_dbo.GuildUsers_dbo.Guilds_GuildID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FMBot.Data.Entities.User", "User")
                        .WithMany("GuildUsers")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK_dbo.GuildUsers_dbo.Users_UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
